---
abstract: 'The great new AnyEvent::Mac::FSEvents!'
author:
  - 'Pedro Melo, C<< <melo at cpan.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Mac-FSEvents
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  Mac::FSEvent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/anyevent--mac--fsevent/
version: 0.01
